"""add password_hash to customer

Revision ID: 690648660cdb
Revises: 7113897da969
Create Date: 2026-02-17 17:34:26.616276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690648660cdb'
down_revision = '7113897da969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
